name: Build Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.0'  # You can specify the Gradle version you need
        cache-enabled: true

    - name: Build APK
      run: ./gradlew assembleRelease  # Use `./gradlew` instead of `gradle` to ensure the local wrapper is used

    - name: Sign app APK
      id: sign_app
      uses: ilharp/sign-android-release@nightly
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: signed-apks
        path: app/build/outputs/apk/release/*-arm64-v8a-release-signed.apk
        if-no-files-found: error
        retention-days: 20
